#ifndef CPPGAME_TEST_ENGINEDEFINES_H
#define CPPGAME_TEST_ENGINEDEFINES_H

#define TILE_SIZE 32
#define CHUNK_SIZE_IN_TILES 16
#define CHUNK_SIZE_IN_PIXELS (32*16)

#define TILESET "assets/tileset.png"

#define MAP_WIDTH_IN_CHUNKS 1000
#define MAP_HEIGHT_IN_CHUNKS 500

#endif //CPPGAME_TEST_ENGINEDEFINES_H
