#ifndef CPPGAME_TEST_ENGINEDEFINES_H
#define CPPGAME_TEST_ENGINEDEFINES_H

#define TILE_SIZE 32
#define CHUNK_SIZE_IN_TILES 16
#define CHUNK_SIZE_IN_PIXELS (32*16)

#endif //CPPGAME_TEST_ENGINEDEFINES_H
